name: Practice Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello Sharmad!"

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la
